version: '3.8'

x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 5s
  retries: 10

x-logging-defaults: &logging-defaults
  driver: 'json-file'
  options:
    max-size: '10m'
    max-file: '5'

networks:
  outside:
    external: true

services:
  web:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    restart: always
    networks:
      - outside
    expose:
      - 3000
    healthcheck:
      test: 'node -e "fetch(''http://127.0.0.1:3000'',{method:''HEAD''}).then(res=>process.exit(res.ok?0:1)).catch(()=>process.exit(1));"'
      <<: *healthcheck-defaults
    logging:
      <<: *logging-defaults
